name: traefik-images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Build and push images
      run: |
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        ./build.ps1
